### ISSUE TITLE
TIMGE General Tests

### ISSUE THREAD

**Issue by marcel-zdziechowicz** [smoolldev/TIMGE#21]
We're adding a demo application that will use every function (as of 30 october 2024) available in TIMGE. There will be a GUI, we're using the brilliant but lacking in some ways Dear ImGUI library.

>[!NOTE]
>Some of these are not related to the tests at all and are changes to the engine that have to be implemented.
>These changes could also be related to the tests.

- [x] FPS (Change to std::chrono)
- [x] Window Title (Get and Set)
- [x] Window Size (Get and Set)
- [x] Add DONT_CARE (ASPECT RATIO, SIZE_LIMITS, POSITION)
- [x] Update Window::Info
- [x] Check if Maximize() and Restore() work as expected
- [x] Check if window position callback is exectued when UpdateMonitor() is called
- [x] Normalize Window
- [x] Window Position (Get and Set)
- [x] Window Aspect Ratio (Get and Set)
- [ ] Window Framebuffer Size (*Set*, when we're rawdogging OpenGL graphics)
- [x] Window Frame Size (Get)
- [x] Window Content Scale
- [x] Window Opacity (Get and Set)
- [x] Fullscreen and Borderless Fullscreen (Get and Set)
- [x] Background Color (Get and Set)
- [x] Monitor (Get and Set)
- [x] Monitor Getters
- [x] SetGamma()
- [ ] Event Processor (Get and Set)
- [x] Keyboard
- [x] Mouse (Pressed and Released)
- [x] Mouse (Disable, Hide, Capture and Restore)
- [x] RawMouseMotion
- [x] Cursor (Add and Delete)
- [x] Cursor (Set and Reset)
- [x] Cursor (GetPosition)
- [x] Scroll (GetOffset)
- [x] GetCursors
- [x] Drop Callback (Adding cursors)
- [ ] Callbacks (All of them motherfuckers, except Gamepad and Joystick)
- [ ] Add callback set functions to CallbackDefs (file name set to change)
- [x] Update window flags in callbacks (BARZ!!!!! :fire:)
- [ ] Add a SmoollEngine easter egg to cameras
- [ ] Add constructor Vector(Type_T value)
- [ ] Add SetAttribute() to Window
- [ ] Add explicit conversions to Vector
- [x] Add VSync
- [ ] Remove TRANSPARENT_FRAMEBUFFER toggle function
- [ ] Enable GL_SRC_ALPHA if TRANSPARENT_FRAMEBUFFER is set in constructor

*Set* - Check issue #23

**Comment by smooll-d** [comment]
Things from this task list will probably be implemented, when implemented we'll reference this issue.

Closing.
